"""Marker-based quiet and contact detection for motion-capture time series.

Public API
----------
- :mod:`contact_detection.quiet` — quiet-interval detection
- :mod:`contact_detection.contact` — support-surface fitting and contact intervals
- :mod:`contact_detection.foot_support` — per-foot air/ground/skateboard classification
- :mod:`contact_detection.intervals` — mask/interval utilities
"""

from .contact import (
    ContactDetectionConfig,
    ContactDetectionResult,
    HeightmapSupportModel,
    LocalPercentileHeightmap,
    PlaneSupportModel,
    SupportCandidate,
    SupportCandidateSet,
    SupportDetectionConfig,
    SupportModel,
    bootstrap_support_surface,
    compute_support_relative_features,
    detect_contact_intervals,
    estimate_contact_offset,
    filter_support_candidates,
    find_support_candidates,
    fit_best_support_surface,
    fit_plane_svd,
    fit_support_model_from_candidates,
    score_contact_features,
)
from .intervals import IntervalSummary, mask_from_intervals, summarize_intervals
from .foot_support import (
    FootSupportClassification,
    FootSupportConfig,
    FootSupportState,
    classify_foot_support_states,
    intervals_by_state,
    load_unified_npz,
)
from .quiet import (
    QuietDetectionConfig,
    QuietDetectionResult,
    QuietSignalType,
    VectorQuietMode,
    clean_mask_by_time,
    compute_quiet_activity_and_spread,
    detect_quiet_intervals,
    intervals_from_mask,
    local_polynomial_derivative,
    quaternion_angular_speed,
    quaternion_local_spread,
    quaternion_standardize_xyzw,
    score_hysteresis_mask,
    time_gaussian_smooth,
    time_window_component_range,
    time_window_range,
    time_window_rms,
    time_window_std,
)

__all__ = [
    "ContactDetectionConfig",
    "ContactDetectionResult",
    "FootSupportClassification",
    "FootSupportConfig",
    "FootSupportState",
    "HeightmapSupportModel",
    "IntervalSummary",
    "LocalPercentileHeightmap",
    "PlaneSupportModel",
    "QuietDetectionConfig",
    "QuietDetectionResult",
    "QuietSignalType",
    "SupportCandidate",
    "SupportCandidateSet",
    "SupportDetectionConfig",
    "SupportModel",
    "VectorQuietMode",
    "bootstrap_support_surface",
    "classify_foot_support_states",
    "clean_mask_by_time",
    "compute_quiet_activity_and_spread",
    "compute_support_relative_features",
    "detect_contact_intervals",
    "detect_quiet_intervals",
    "estimate_contact_offset",
    "filter_support_candidates",
    "find_support_candidates",
    "fit_best_support_surface",
    "fit_plane_svd",
    "fit_support_model_from_candidates",
    "intervals_from_mask",
    "intervals_by_state",
    "local_polynomial_derivative",
    "load_unified_npz",
    "mask_from_intervals",
    "quaternion_angular_speed",
    "quaternion_local_spread",
    "quaternion_standardize_xyzw",
    "score_contact_features",
    "score_hysteresis_mask",
    "summarize_intervals",
    "time_gaussian_smooth",
    "time_window_component_range",
    "time_window_range",
    "time_window_rms",
    "time_window_std",
]
